apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-app.fullname" . }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.container.port }}
      targetPort: http
      name: http
  selector:
    {{- include "generic-app.selectorLabels" . | nindent 4 }} 