apiVersion: ec2.services.k8s.aws/v1alpha1
kind: Instance
metadata:
  name: ack-example-instance
  labels:
    app: example-app
    environment: development
    managed-by: ack
spec:
  imageID: ami-0abcdef1234567890  # Replace with actual AMI ID for us-east-1
  instanceType: t3.micro
  keyName: my-key-pair  # Replace with your key pair name
  subnetID: subnet-12345abcde  # Replace with your subnet ID
  securityGroupIDs:
  - sg-12345abcde  # Replace with your security group ID
  userData: |
    #!/bin/bash
    yum update -y
    yum install -y docker
    systemctl start docker
    systemctl enable docker
    echo "Instance created via ACK!" > /home/ec2-user/ack-created.txt
  tags:
  - key: Name
    value: ACK-Example-Instance
  - key: Environment
    value: development
  - key: Project
    value: platform-vibez
  - key: ManagedBy
    value: ack-controller 