apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
  annotations:
    policies.kyverno.io/category: Platform Security
    policies.kyverno.io/description: "Disallows the use of 'latest' tag for container images in team namespaces to ensure version pinning and deployment consistency"
spec:
  background: true
  validationFailureAction: Enforce
  rules:
  - name: check-image-tag-pods
    match:
      resources:
        kinds:
        - Pod
        namespaces:
        - "*team*"
    validate:
      message: "Using 'latest' tag is not allowed in team namespaces. Please specify a specific version tag for better deployment consistency and rollback capabilities."
      pattern:
        spec:
          containers:
          - image: "!*:latest"
          =(initContainers):
          - image: "!*:latest"
  - name: check-image-tag-deployments
    match:
      resources:
        kinds:
        - Deployment
        namespaces:
        - "*team*"
    validate:
      message: "Using 'latest' tag is not allowed in team namespaces. Please specify a specific version tag for better deployment consistency and rollback capabilities."
      pattern:
        spec:
          template:
            spec:
              containers:
              - image: "!*:latest"
              =(initContainers):
              - image: "!*:latest"
  - name: check-image-tag-daemonsets
    match:
      resources:
        kinds:
        - DaemonSet
        namespaces:
        - "*team*"
    validate:
      message: "Using 'latest' tag is not allowed in team namespaces. Please specify a specific version tag for better deployment consistency and rollback capabilities."
      pattern:
        spec:
          template:
            spec:
              containers:
              - image: "!*:latest"
              =(initContainers):
              - image: "!*:latest"
  - name: check-image-tag-statefulsets
    match:
      resources:
        kinds:
        - StatefulSet
        namespaces:
        - "*team*"
    validate:
      message: "Using 'latest' tag is not allowed in team namespaces. Please specify a specific version tag for better deployment consistency and rollback capabilities."
      pattern:
        spec:
          template:
            spec:
              containers:
              - image: "!*:latest"
              =(initContainers):
              - image: "!*:latest"
  - name: check-image-tag-jobs
    match:
      resources:
        kinds:
        - Job
        namespaces:
        - "*team*"
    validate:
      message: "Using 'latest' tag is not allowed in team namespaces. Please specify a specific version tag for better deployment consistency and rollback capabilities."
      pattern:
        spec:
          template:
            spec:
              containers:
              - image: "!*:latest"
              =(initContainers):
              - image: "!*:latest"
  - name: check-image-tag-cronjobs
    match:
      resources:
        kinds:
        - CronJob
        namespaces:
        - "*team*"
    validate:
      message: "Using 'latest' tag is not allowed in team namespaces. Please specify a specific version tag for better deployment consistency and rollback capabilities."
      pattern:
        spec:
          jobTemplate:
            spec:
              template:
                spec:
                  containers:
                  - image: "!*:latest"
                  =(initContainers):
                  - image: "!*:latest"
  - name: check-image-tag-knative-services
    match:
      resources:
        kinds:
        - serving.knative.dev/v1/Service
        namespaces:
        - "*team*"
    validate:
      message: "Using 'latest' tag is not allowed in team namespaces. Please specify a specific version tag for better deployment consistency and rollback capabilities."
      pattern:
        spec:
          template:
            spec:
              containers:
              - image: "!*:latest"
              =(initContainers):
              - image: "!*:latest" 