apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
  annotations:
    policies.kyverno.io/title: Disallow Latest Tag
    policies.kyverno.io/category: Platform Security
    policies.kyverno.io/description: >-
      Prevents use of 'latest' tag in container images for reproducible deployments in team namespaces.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: check-image-tag
    match:
      any:
      - resources:
          kinds:
          - Deployment
          namespaces:
          - "team-*"
          - "chainsaw-*"
    validate:
      message: "Container images must not use 'latest' tag. Specify a version tag."
      deny:
        conditions:
          any:
          - key: "{{ request.object.spec.template.spec.containers[*].image }}"
            operator: AnyIn
            value: ["*:latest"]
          - key: "{{ request.object.spec.template.spec.containers[*].image | [?ends_with(@, ':latest')] | length(@) }}"
            operator: GreaterThan
            value: 0 